version: '3'

services:
  db:
    container_name: brickeval_db_1
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

